from collections import deque
import json
import pickle
import re
from typing import List
from overcooked_ai_py.agents.agent import Agent
from overcooked_ai_py.mdp.overcooked_mdp import OvercookedGridworld
from overcooked_ai_py.planning.planners import MotionPlanner, NO_COUNTERS_PARAMS
from overcooked_ai_py.mdp.actions import Action, Direction
from llm.ollama.ollama_client import query_ollama
import os
from openai import OpenAI
from llm.memory.vector_memory import VectorMemory
from state_graph import StateGraphGenerator, StateGraph, get_state_graph_generator
from unified_state_graph import get_unified_state_graph  # NEW: Unified state graph
from plan_session import PLAN_STORE
from game_mechanics import get_mechanics_for_task
from optimized_coordination_system import get_coordination_system, quick_coordinate

UNIFIED_OVERCOOKED_MODEL = "ft:gpt-4.1-mini-2025-04-14:personal:ap-one-model:C6I6sz96"

# Model mappings for different recipes (keeping for backward compatibility)
OVERCOOKED_MODELS = {
    "onion_raw": "ft:gpt-4o-mini-2024-07-18:personal:ap-onion:C2PPw6JD",
    "onion_chopped": "ft:gpt-4o-mini-2024-07-18:personal:ap-chopped-onion-soup:BysMfU2m", 
    "tomato_raw": "ft:gpt-4o-mini-2024-07-18:personal:ap-tomato-soup:BysMfU2m",
    "tomato_chopped": "ft:gpt-4o-mini-2024-07-18:personal:ap-chopped-tomato-soup:BysMfU2m",
    "onion_raw_tomato_raw": "ft:gpt-4o-mini-2024-07-18:personal:ap-onion-tomato-soup:BysMfU2m",
    "onion_chopped_tomato_raw": "ft:gpt-4o-mini-2024-07-18:personal:ap-chopped-onion-tomato-soup:BysMfU2m",
    "onion_raw_tomato_chopped": "ft:gpt-4o-mini-2024-07-18:personal:ap-onion-chopped-tomato-soup:BysMfU2m",
    "onion_chopped_tomato_chopped": "ft:gpt-4o-mini-2024-07-18:personal:ap-chopped-onion-chopped-tomato:C3YYuvHe"
}

# Default model fallback
DEFAULT_OVERCOOKED_MODEL = UNIFIED_OVERCOOKED_MODEL  # NEW: Use unified model as default

# Current single model (keeping for backward compatibility)
OVERCOOKED_MODEL = UNIFIED_OVERCOOKED_MODEL  # NEW: Use unified model
# OVERCOOKED_MODEL = "gpt-4o-mini"
# OVERCOOKED_MODEL = "nothing"

def parse_recipe_components(task_title: str) -> str:
    """
    Parse task title to determine which model to use.
    Returns a key that maps to OVERCOOKED_MODELS.
    
    The word 'chopped' must come before the ingredient name to modify it.
    """
    task_title = task_title.lower()
    
    # Check for single ingredient recipes
    if "onion" in task_title and "tomato" not in task_title:
        if "chopped" in task_title and task_title.find("chopped") < task_title.find("onion"):
            return "onion_chopped"
        else:
            return "onion_raw"
    
    elif "tomato" in task_title and "onion" not in task_title:
        if "chopped" in task_title and task_title.find("chopped") < task_title.find("tomato"):
            return "tomato_chopped"
        else:
            return "tomato_raw"
    
    # Check for dual ingredient recipes
    elif "onion" in task_title and "tomato" in task_title:
        # For "Chopped Onion and Chopped Tomato", both are chopped
        # Check if "chopped" appears before "onion" (first ingredient)
        onion_chopped = ("chopped" in task_title and 
                        task_title.find("chopped") < task_title.find("onion"))
        
        # Check if "chopped" appears before "tomato" (second ingredient)
        # Look for "chopped" after "and" or "&" but before "tomato"
        and_pos = task_title.find("and")
        ampersand_pos = task_title.find("&")
        separator_pos = max(and_pos, ampersand_pos) if and_pos != -1 or ampersand_pos != -1 else -1
        
        tomato_chopped = False
        if separator_pos != -1:
            # Check if there's "chopped" between separator and "tomato"
            tomato_section = task_title[separator_pos:]
            tomato_chopped = ("chopped" in tomato_section and 
                            tomato_section.find("chopped") < tomato_section.find("tomato"))
        
        onion_state = "chopped" if onion_chopped else "raw"
        tomato_state = "chopped" if tomato_chopped else "raw"
        
        return f"onion_{onion_state}_tomato_{tomato_state}"
    
    # Fallback for unknown recipes
    return "default"

# The old OVERCOOKED_GAME_MECHANICS has been replaced with dynamic task-specific mechanics
# Generated by the game_mechanics module

def query_openai(prompt: str, model: str = None, temperature: float = 0.0) -> str:
    """Query the OpenAI API with the given prompt and return the response text."""
    # Use the default model if none specified
    if model is None:
        model = DEFAULT_OVERCOOKED_MODEL
    
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY environment variable not set.")
   
    client = OpenAI(api_key=api_key)
   
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            max_tokens=256,
        )
       
        content = response.choices[0].message.content
        if content is not None:
            return content.strip()
        return ""
       
    except Exception as e:
        print(f"Error querying OpenAI: {e}")
        return ""

def _bfs_fallback(start, goal, terrain, goal_orientation=None):
    """Return a list of (delta_col, delta_row) moves to walk from start to goal on terrain."""
    H, W = len(terrain), len(terrain[0])
    visited = {start}
    parent = {}
    queue = deque([start])

    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]

    while queue:
        col, row = queue.popleft()
        if (col, row) == goal:
            path = []
            cur = goal
            while cur != start:
                prev = parent[cur]
                dc = cur[0] - prev[0]
                dr = cur[1] - prev[1]
                path.append((dc, dr))
                cur = prev
            path = list(reversed(path))  
            
            if goal_orientation is not None and path[-1] != goal_orientation:
                if goal_orientation == (1, 0): 
                    path.append((1, 0))
                elif goal_orientation == (-1, 0):  
                    path.append((-1, 0))
                elif goal_orientation == (0, 1):  
                    path.append((0, 1))
                elif goal_orientation == (0, -1):  
                    path.append((0, -1))

            path.append(Action.INTERACT)
            return path

        for dc, dr in directions:
            new_col = col + dc
            new_row = row + dr
            if (
                0 <= new_row < H and
                0 <= new_col < W and
                terrain[new_row][new_col] != 'X' and
                (new_col, new_row) not in visited
            ):
                visited.add((new_col, new_row))
                parent[(new_col, new_row)] = (col, row)
                queue.append((new_col, new_row))

    return []

class CoordinatedActionPredictorAgent(Agent):
    """
    An agent that uses coordinated state graph navigation for goal-directed behavior.
    
    This agent:
    1. Uses a state graph to navigate toward the goal
    2. Predicts human behavior and coordinates accordingly
    3. Balances goal progress with coordination quality
    4. Adapts to human actions dynamically
    """
    
    def __init__(self):
        super().__init__()
        self.mdp = None
        self.planner = None
        self.ingredient_spawns = []
        self.onion_spawns = []
        self.tomato_spawns = []
        self.stove_tiles = []
        self.dish_spawns = []
        self.delivery_tiles = []
        self.staging_tiles = []
        self.onion_chopping_stations = []
        self.tomato_chopping_stations = []
        self.last_info = None
        self.cleaned_terrain = None
        self.last_summary = None
        self.agent_index = None
        self.memory = VectorMemory()
        self.onion_chopped = False
        self.tomato_chopped = False
        self.onion_washed = False
        self.tomato_washed = False
        
        # State graph - using optimized coordination system instead
        self.state_graph = None
        # Defer state graph initialization until plan is set
        
        # Action execution state - like action_predictor.py
        self.current_action_plan = []
        self.current_action_index = 0
        
        # NEW: Set the model directly for unified state graph
        self.selected_model = UNIFIED_OVERCOOKED_MODEL
        print(f"Selected unified model: {self.selected_model}")
        
        # NEW: Set default task title for unified state graph
        self.task_title = "Unknown Task"

    def _initialize_state_graph(self):
        """Initialize the unified state graph and coordination system"""
        print("Initializing unified state graph...")
        
        # Get task title to determine which model to use
        task_title = getattr(self, 'plan', None)
        if task_title and hasattr(task_title, 'task_title'):
            task_title = task_title.task_title
        else:
            task_title = "Unknown Task"
        
        print(f"Task title: {task_title}")
        
        # NEW: Always use the unified model for all recipes
        self.selected_model = UNIFIED_OVERCOOKED_MODEL
        print(f"Selected unified model: {self.selected_model}")
        
        # Store task information for mechanics selection
        self.task_title = task_title
        
        # NEW: Load the unified state graph (handles all recipes)
        cache_file = os.path.join(os.path.dirname(__file__), '..', 'cached_unified_state_graph.pkl')
        if os.path.exists(cache_file):
            print(f"Loading unified state graph from cache...")
            try:
                with open(cache_file, 'rb') as f:
                    self.state_graph = pickle.load(f)
                print(f"Unified state graph loaded from cache with {len(self.state_graph.nodes)} nodes")
            except (EOFError, pickle.UnpicklingError, Exception) as e:
                print(f"Unified cache file corrupted, regenerating state graph... (Error: {e})")
                # Remove the corrupted cache file
                try:
                    os.remove(cache_file)
                except:
                    pass
                # Fall through to generate new unified state graph
                self._generate_unified_state_graph()
        else:
            print(f"Unified cache not found, generating unified state graph...")
            self._generate_unified_state_graph()
        
        # No need for old coordination manager - using optimized system
        
    def _generate_unified_state_graph(self):
        """Generate unified state graph for all recipes"""
        print("Generating unified state graph...")
        
        # Get the unified state graph (handles all recipe types)
        self.state_graph = get_unified_state_graph()
        print(f"Unified state graph generated with {len(self.state_graph.nodes)} nodes")
        
        # Save to unified cache
        cache_file = os.path.join(os.path.dirname(__file__), '..', 'cached_unified_state_graph.pkl')
        print(f"Saving unified state graph to cache...")
        with open(cache_file, 'wb') as f:
            pickle.dump(self.state_graph, f)
        print("Unified state graph cached for future use")

    def set_agent_index(self, agent_index: int):
        super().set_agent_index(agent_index)
        self.agent_index = agent_index

    def set_plan(self, session_id: str):
        """Attach the full PlanSession to this agent and filter for primary tasks only."""
        self.plan = PLAN_STORE[session_id]
        
        # NEW: Filter plan to extract only primary tasks for LLM context
        self.primary_tasks = self._extract_primary_tasks_from_plan()
        print(f"Full plan loaded with {len(self.plan.events)} total tasks")
        print(f"Filtered to {len(self.primary_tasks)} primary tasks for LLM")
        
        # NEW: Set task title from plan for unified state graph
        if hasattr(self.plan, 'task_title'):
            self.task_title = self.plan.task_title
            print(f"Task title set from plan: {self.task_title}")
        
        # Initialize state graph now that we have the plan with task title
        self._initialize_state_graph()
        print("State graph initialization enabled")
    
    def _extract_primary_tasks_from_plan(self) -> List[str]:
        """
        NEW: Extract only primary tasks from the full plan.
        This filters out secondary tasks so the LLM only sees human actions.
        The plan structure has arrays of primary actions per step.
        """
        if not self.plan or not hasattr(self.plan, 'events'):
            return []
        
        # NEW: Handle the actual plan structure with arrays of primary actions
        primary_tasks = []
        for event in self.plan.events:
            # Extract primary actions from the 'primary' field (which is an array)
            if 'primary' in event and isinstance(event['primary'], list):
                for primary_action in event['primary']:
                    # Skip NOOP actions as they're not meaningful for LLM context
                    if primary_action != 'NOOP':
                        primary_tasks.append(primary_action)
        
        # print(f"🔍 Extracted primary tasks from plan: {primary_tasks}")
        return primary_tasks

    TERRAIN_MAPPING = {
        "X": "Wall",
        "P": "Stove",
        "O": "Onions",
        "T": "Tomatoes",  
        "D": "DishSpawn",
        "S": "Serving",
        " ": "Empty"
    }

    def set_mdp(self, mdp: OvercookedGridworld):
        super().set_mdp(mdp)
        self.mdp = mdp
        terrain = mdp.terrain_mtx
        self.ingredient_spawns = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c in ('O', 'T')]
        self.onion_spawns = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c == 'O']
        self.tomato_spawns = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c == 'T']
        self.stove_tiles = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c == 'P']
        self.dish_spawns = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c == 'D']
        self.delivery_tiles = [(j, i)
                            for i, row in enumerate(terrain)
                            for j, c in enumerate(row)
                            if c == 'S']
        
        # Assign staging stations per stove with directional logic
        self.onion_staging_tiles = []
        self.tomato_staging_tiles = []
        self.dish_staging_tiles = []
        H, W = len(terrain), len(terrain[0]) 
        
        for (stove_c, stove_r) in self.stove_tiles:
            adjacent_staging = []
            for dc, dr in [(1,0), (-1,0), (0,1), (0,-1)]:
                nc, nr = stove_c + dc, stove_r + dr
                if 0 <= nr < H and 0 <= nc < W and terrain[nr][nc] == 'X':
                    adjacent_staging.append((nc, nr, dc, dr))
            
            left_stations = [(c, r) for c, r, dc, dr in adjacent_staging if dc == -1]
            right_stations = [(c, r) for c, r, dc, dr in adjacent_staging if dc == 1]  
            top_stations = [(c, r) for c, r, dc, dr in adjacent_staging if dr == -1]   
            bottom_stations = [(c, r) for c, r, dc, dr in adjacent_staging if dr == 1]
            
            if left_stations:
                self.onion_staging_tiles.extend(left_stations)
            elif bottom_stations:
                self.onion_staging_tiles.extend(bottom_stations)
            
            # if right_stations:
            #     self.dish_staging_tiles.extend(right_stations)
            # elif top_stations:
            #     self.dish_staging_tiles.extend(top_stations)

            self.tomato_staging_tiles = self.onion_staging_tiles.copy()
            self.dish_staging_tiles = self.onion_staging_tiles.copy() # Moving the dish staging tile to agent side
            self.soup_staging_tiles = self.dish_staging_tiles

        # Get layout name for special handling
        layout_name = getattr(mdp, 'layout_name', 'unknown')
        
        # Create chopping stations
        self.onion_chopping_stations = []
        self.tomato_chopping_stations = []
        
        if layout_name == 'cramped_room_tomato':
            # For cramped_room_tomato: use hardcoded chopping station at (0,2)
            self.onion_chopping_stations = [(0, 2)]
            self.tomato_chopping_stations = [(0, 2)]
        else:
            # Use dynamic detection for other layouts
            for staging_pos in self.onion_staging_tiles:
                staging_c, staging_r = staging_pos
                for dc, dr in [(-1, 0), (0, -1)]:
                    chopping_c, chopping_r = staging_c + dc, staging_r + dr
                    if (0 <= chopping_r < H and 0 <= chopping_c < W and 
                        terrain[chopping_r][chopping_c] == 'X' and
                        (chopping_c, chopping_r) not in self.onion_chopping_stations):
                        self.onion_chopping_stations.append((chopping_c, chopping_r))
                        break
            
            self.tomato_chopping_stations = self.onion_chopping_stations.copy()

        # Create sink stations
        self.sink_stations = []
        
        if layout_name == 'counter_circuit':
            # For counter_circuit: sink at (0,2)
            self.sink_stations.append((0, 2))
        elif layout_name == 'cramped_room_tomato':
            # For cramped_room_tomato: sink at (2,3)
            self.sink_stations.append((2, 3))
        
                # Compute frontiers
        self.ingredient_frontier = self._compute_frontier(self.ingredient_spawns, terrain)
        self.onion_frontier = self._compute_frontier(self.onion_spawns, terrain)
        self.tomato_frontier = self._compute_frontier(self.tomato_spawns, terrain)
        self.stove_frontier = self._compute_frontier(self.stove_tiles, terrain) 
        self.dish_frontier = self._compute_frontier(self.dish_spawns, terrain)
        self.delivery_frontier = self._compute_frontier(self.delivery_tiles, terrain)
        self.onion_staging_frontier = self._compute_frontier(self.onion_staging_tiles, terrain)
        self.tomato_staging_frontier = self._compute_frontier(self.tomato_staging_tiles, terrain)
        self.dish_staging_frontier = self._compute_frontier(self.dish_staging_tiles, terrain)
        self.soup_staging_frontier = self._compute_frontier(self.soup_staging_tiles, terrain)
        self.onion_chopping_frontier = self._compute_frontier(self.onion_chopping_stations, terrain)
        self.tomato_chopping_frontier = self._compute_frontier(self.tomato_chopping_stations, terrain)
        self.sink_frontier = self._compute_frontier(self.sink_stations, terrain)
        
        my_goals = {
            'ingredient': self.ingredient_spawns,
            'pot': self.stove_tiles,
            'dish': self.dish_spawns,
            'delivery': self.delivery_tiles
        } 
        
        self.cleaned_terrain = [
            [self.TERRAIN_MAPPING.get(cell, "Unknown") for cell in row]
            for row in terrain
        ]

        self.planner = MotionPlanner(mdp, counter_goals=my_goals)

    def _compute_frontier(self, tiles, terrain):
        """Return the set of walkable tiles adjacent to any tile in 'tiles'."""
        H, W = len(terrain), len(terrain[0])
        frontier = set()
        WALKABLE = {' '}

        for c, r in tiles:
            for dc, dr in [(1,0), (-1,0), (0,1), (0,-1)]:
                nc, nr = c + dc, r + dr
                if (
                    0 <= nr < H and 
                    0 <= nc < W and 
                    terrain[nr][nc] in WALKABLE
                ):
                    orient = (-dc, -dr)
                    frontier.add(((nc, nr), orient))
        return list(frontier)

    def summarize_state(self, state, info):
        """Extract state predicates for the LLM (same as original)"""
        sd = state.to_dict()

        def held_item(player_dict):
            held = player_dict["held_object"]
            if held is None:
                return "none"
            if held.get("name") in ("onion", "tomato"):
                return held["name"]
            if held.get("ingredient") in ("onion", "tomato"):
                return held["ingredient"]
            if held.get("name") in ("dish", "soup"):
                return held["name"]
            return "none"

        me = sd["players"][self.agent_index]
        them = sd["players"][1 - (self.agent_index or 0)]
        agent_item = held_item(me)
        partner_item = held_item(them)

        onion_hand = "none"
        if agent_item == "onion":
            onion_hand = "agent"
        elif partner_item == "onion":
            onion_hand = "partner"

        tomato_hand = "none"
        if agent_item == "tomato":
            tomato_hand = "agent"
        elif partner_item == "tomato":
            tomato_hand = "partner"

        dish_hand = "none"
        if agent_item == "dish":
            dish_hand = "agent"
        elif partner_item == "dish":
            dish_hand = "partner"

        soup_hand = "none"
        if agent_item == "soup":
            soup_hand = "agent"
        elif partner_item == "soup":
            soup_hand = "partner"

        tile_contents = {}
        onion_in_pot = False
        tomato_in_pot = False
        soup_cooking = False
        soup_ready = False
        soup_in_pot_not_cooking = False
        
        for obj in sd["objects"]:
            p = tuple(obj["position"])
            name = obj.get("ingredient") or obj.get("name")
            tile_contents.setdefault(p, []).append(name)
            
            if obj.get("name") == "soup" and obj.get("_ingredients"):
                for ingredient in obj["_ingredients"]:
                    ing_name = ingredient.get("name")
                    if ing_name:
                        tile_contents.setdefault(p, []).append(ing_name)
                
                if p in self.stove_tiles:
                    for ingredient in obj["_ingredients"]:
                        ing_name = ingredient.get("name")
                        if ing_name in ("onion", "chopped_onion"):
                            onion_in_pot = True
                        elif ing_name in ("tomato", "chopped_tomato"):
                            tomato_in_pot = True
                    
                    cooking_tick = obj.get("cooking_tick", -1)
                    is_cooking = obj.get("is_cooking", False)
                    is_ready = obj.get("is_ready", False)
                    
                    if is_cooking and cooking_tick >= 1:
                        soup_cooking = True
                    elif is_ready:
                        soup_ready = True
                    elif cooking_tick == -1:
                        soup_in_pot_not_cooking = True

        onion_staged = any(
            "onion" in tile_contents.get(pos, [])
            for pos in self.onion_staging_tiles
        )
        
        onion_at_chopping = any(
            "onion" in tile_contents.get(pos, [])
            for pos in self.onion_chopping_stations
        )
        
        if onion_at_chopping:
            self.onion_chopped = True

        tomato_staged = any(
            "tomato" in tile_contents.get(pos, [])
            for pos in self.tomato_staging_tiles
        )
        
        tomato_at_chopping = any(
            "tomato" in tile_contents.get(pos, [])
            for pos in self.tomato_chopping_stations
        )
        
        if tomato_at_chopping:
            self.tomato_chopped = True

        dish_staged = any(
            "dish" in tile_contents.get(pos, [])
            for pos in self.dish_staging_tiles
        )

        soup_staged = any(
            "soup" in tile_contents.get(pos, [])
            for pos in self.soup_staging_tiles
        )

        soup_served = False
        if info:
            soup_served = any(
                info.get("event_infos", {})
                    .get("soup_delivery", [False, False])
            )

        if soup_served:
            self.onion_chopped = False
            self.tomato_chopped = False
            self.onion_washed = False
            self.tomato_washed = False

        # Check sink-related states
        onion_at_sink = any(
            "onion" in tile_contents.get(pos, [])
            for pos in self.sink_stations
        )
        
        tomato_at_sink = any(
            "tomato" in tile_contents.get(pos, [])
            for pos in self.sink_stations
        )
        
        # Track washing completion state
        # When an ingredient is at the sink, it means it's being washed or has been washed
        if onion_at_sink:
            self.onion_washed = True
            
        if tomato_at_sink:
            self.tomato_washed = True

        return {
            "onion_hand": onion_hand,
            "onion_staged": onion_staged,
            "onion_at_chopping": onion_at_chopping,
            "onion_chopped": self.onion_chopped,
            "onion_at_sink": onion_at_sink,
            "onion_washed": self.onion_washed,
            "tomato_hand": tomato_hand,
            "tomato_staged": tomato_staged,
            "tomato_at_chopping": tomato_at_chopping,
            "tomato_chopped": self.tomato_chopped,
            "tomato_at_sink": tomato_at_sink,
            "tomato_washed": self.tomato_washed,
            "onion_in_pot": onion_in_pot,
            "tomato_in_pot": tomato_in_pot,
            "soup_cooking": soup_cooking,
            "soup_ready": soup_ready,
            "soup_in_pot_not_cooking": soup_in_pot_not_cooking,
            "dish_hand": dish_hand,
            "dish_staged": dish_staged,
            "soup_hand": soup_hand,
            "soup_staged": soup_staged,
            "soup_served": soup_served
        }
    
    def _generate_plan_to_goal(self, current_state: dict) -> str:
        """
        Generate a plan from current state to goal state using A* pathfinding.
        Returns the next action from the optimal path to goal.
        """
        # Define goal state (soup served)
        goal_state = {
            'onion_hand': 'none',
            'onion_staged': False,
            'onion_at_chopping': False,
            'onion_chopped': False,
            'onion_at_sink': False,
            'onion_washed': False,
            'tomato_hand': 'none',
            'tomato_staged': False,
            'tomato_at_chopping': False,
            'tomato_chopped': False,
            'tomato_at_sink': False,
            'tomato_washed': False,
            'onion_in_pot': False,
            'tomato_in_pot': False,
            'soup_cooking': False,
            'soup_ready': False,
            'soup_in_pot_not_cooking': False,
            'dish_hand': 'none',
            'dish_staged': False,
            'soup_hand': 'none',
            'soup_staged': False,
            'soup_served': True  # Goal state
        }
        
        # Get current and goal node IDs using our own lookup method
        current_node_id = self._get_node_id_for_state(current_state)
        goal_node_id = self._get_node_id_for_state(goal_state)
        
        if not current_node_id or not goal_node_id:
            return self._get_fallback_action(current_state)  # Use fallback when no nodes found

        # Find path from current state to goal
        try:
            path = self.state_graph.find_path_to_goal(current_node_id, goal_node_id)
            
            if len(path) < 2:
                return self._get_fallback_action(current_state)  # Use fallback when no path found
            
            # Get the next action from the path
            next_node_id = path[1]  # First node is current, second is next
            for edge in self.state_graph.get_edges_from(current_node_id):
                if edge.to_node == next_node_id:
                    return edge.action
            
            return self._get_fallback_action(current_state)  # Use fallback when no edge found
            
        except Exception as e:
            return self._get_fallback_action(current_state)  # Use fallback on any exception

    def _get_fallback_action(self, current_state: dict) -> str:
        """
        Simple heuristic-based action selection when state graph planning fails.
        This provides a basic fallback strategy for goal-directed behavior.
        """
        # Priority-based action selection
        # 1. If we have soup in hand, serve it
        if current_state['soup_hand'] == 'agent':
            return 'place(soup)'
        
        # 2. If soup is ready and staged, pick it up
        if current_state['soup_ready'] and current_state['soup_staged'] and current_state['soup_hand'] == 'none':
            return 'pickup(soup)'
        
        # 3. If we have chopped onion, place it at staging
        if current_state['onion_hand'] == 'agent' and current_state['onion_chopped']:
            return 'place(chopped_onion)'
        
        # 4. If we have chopped tomato, place it at staging
        if current_state['tomato_hand'] == 'agent' and current_state['tomato_chopped']:
            return 'place(chopped_tomato)'
        
        # 5. If we have raw onion, chop it
        if current_state['onion_hand'] == 'agent' and not current_state['onion_chopped']:
            return 'place(onion, chopping_station)'
        
        # 6. If we have raw tomato, chop it
        if current_state['tomato_hand'] == 'agent' and not current_state['tomato_chopped']:
            return 'place(tomato, chopping_station)'
        
        # 7. If onion is at chopping and chopped, pick it up
        if current_state['onion_at_chopping'] and current_state['onion_chopped'] and current_state['onion_hand'] == 'none':
            return 'pickup(chopped_onion)'
        
        # 8. If tomato is at chopping and chopped, pick it up
        if current_state['tomato_at_chopping'] and current_state['tomato_chopped'] and current_state['tomato_hand'] == 'none':
            return 'pickup(chopped_tomato)'
        
        # 9. If we have dish, place it at staging
        if current_state['dish_hand'] == 'agent':
            return 'place(dish)'
        
        # 10. If soup is cooking and we don't have dish, get dish
        if current_state['soup_cooking'] and current_state['dish_hand'] == 'none':
            return 'pickup(dish)'
        
        # 11. If we have nothing and onion is available, get onion
        if (current_state['onion_hand'] == 'none' and not current_state['onion_staged'] and 
            not current_state['onion_at_chopping'] and not current_state['onion_in_pot']):
            return 'pickup(onion)'
        
        # 12. If we have nothing and tomato is available, get tomato
        if (current_state['tomato_hand'] == 'none' and not current_state['tomato_staged'] and 
            not current_state['tomato_at_chopping'] and not current_state['tomato_in_pot']):
            return 'pickup(tomato)'
        
        # 13. If onion is washed and at sink, pick it up (washing complete)
        if current_state['onion_washed'] and current_state['onion_at_sink'] and current_state['onion_hand'] == 'none':
            return 'pickup(onion)'
        
        # 14. If tomato is washed and at sink, pick it up (washing complete)
        if current_state['tomato_washed'] and current_state['tomato_at_sink'] and current_state['tomato_hand'] == 'none':
            return 'pickup(tomato)'
        
        # Default: no action needed
        return 'NOOP'

    def _get_node_id_for_state(self, state: dict) -> str:
        """
        Get node ID for a state using the state graph mapping.
        This replaces the old coordination manager's node ID lookup.
        """
        if not self.state_graph:
            return None
            
        # Use the state graph's mapping if available
        if hasattr(self.state_graph, 'state_to_node_id'):
            state_key = json.dumps(state, sort_keys=True)
            node_id = self.state_graph.state_to_node_id.get(state_key)
            if node_id:
                return node_id
        
        # Try to find a matching node by comparing state summaries
        state_key = json.dumps(state, sort_keys=True)
        print(f"🔍 Looking for state: {state_key}")
        print(f"   Available mappings: {len(self.state_graph.state_to_node_id) if hasattr(self.state_graph, 'state_to_node_id') else 0}")
        
        for node_id, node in self.state_graph.nodes.items():
            node_state_key = json.dumps(node.state_summary, sort_keys=True)
            if node_state_key == state_key:
                print(f"   ✅ Found matching node: {node_id}")
                return node_id
        
        print(f"   ❌ No exact match found")
        # Fallback to simple hash-based ID if no exact match found
        return f"state_{hash(state_key) % 1000000:06d}"

    def _is_blocking_important_tile(self, my_pos: tuple, state) -> bool:
        """
        Check if the agent is currently blocking an important staging tile.
        Returns True if blocking, False otherwise.
        """
        # Get all important tiles that shouldn't be blocked
        important_tiles = set()
        
        # Add all staging tiles
        important_tiles.update(self.onion_staging_tiles)
        important_tiles.update(self.tomato_staging_tiles)
        important_tiles.update(self.dish_staging_tiles)
        important_tiles.update(self.soup_staging_tiles)
        
        # Add all chopping stations
        important_tiles.update(self.onion_chopping_stations)
        important_tiles.update(self.tomato_chopping_stations)
        
        # Add all sink stations
        important_tiles.update(self.sink_stations)
        
        # Add all frontier tiles (adjacent to important locations)
        important_tiles.update([pos for pos, _ in self.ingredient_frontier])
        important_tiles.update([pos for pos, _ in self.onion_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_frontier])
        important_tiles.update([pos for pos, _ in self.stove_frontier])
        important_tiles.update([pos for pos, _ in self.dish_frontier])
        important_tiles.update([pos for pos, _ in self.delivery_frontier])
        important_tiles.update([pos for pos, _ in self.onion_staging_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_staging_frontier])
        important_tiles.update([pos for pos, _ in self.dish_staging_frontier])
        important_tiles.update([pos for pos, _ in self.soup_staging_frontier])
        important_tiles.update([pos for pos, _ in self.onion_chopping_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_chopping_frontier])
        
        # Check if current position is blocking an important tile
        is_blocking = my_pos in important_tiles
        
        return is_blocking

    def _find_safe_position(self, my_pos: tuple, state) -> tuple:
        """
        Find a safe position to move to that doesn't block important tiles.
        Returns (new_position, action_plan) or (my_pos, []) if no safe move found.
        """
        if not self.mdp:
            return my_pos, []
            
        terrain = self.mdp.terrain_mtx
        H, W = len(terrain), len(terrain[0])
        
        # Get all important tiles to avoid
        important_tiles = set()
        important_tiles.update(self.onion_staging_tiles)
        important_tiles.update(self.tomato_staging_tiles)
        important_tiles.update(self.dish_staging_tiles)
        important_tiles.update(self.soup_staging_tiles)
        important_tiles.update(self.onion_chopping_stations)
        important_tiles.update(self.tomato_chopping_stations)
        important_tiles.update(self.sink_stations)
        important_tiles.update([pos for pos, _ in self.ingredient_frontier])
        important_tiles.update([pos for pos, _ in self.onion_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_frontier])
        important_tiles.update([pos for pos, _ in self.stove_frontier])
        important_tiles.update([pos for pos, _ in self.dish_frontier])
        important_tiles.update([pos for pos, _ in self.delivery_frontier])
        important_tiles.update([pos for pos, _ in self.onion_staging_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_staging_frontier])
        important_tiles.update([pos for pos, _ in self.dish_staging_frontier])
        important_tiles.update([pos for pos, _ in self.soup_staging_frontier])
        important_tiles.update([pos for pos, _ in self.onion_chopping_frontier])
        important_tiles.update([pos for pos, _ in self.tomato_chopping_frontier])
        important_tiles.update([pos for pos, _ in self.sink_frontier])
        
        # Get other player position to avoid blocking them
        other_player_pos = state.player_positions[1 - self.agent_index]
        
        # Find safe positions within reasonable distance (max 3 steps)
        safe_positions = []
        for distance in range(1, 4):  # Check 1, 2, 3 steps away
            for dc in range(-distance, distance + 1):
                for dr in range(-distance, distance + 1):
                    if abs(dc) + abs(dr) == distance:  # Manhattan distance
                        new_col = my_pos[0] + dc
                        new_row = my_pos[1] + dr
                        
                        # Check bounds
                        if 0 <= new_row < H and 0 <= new_col < W:
                            new_pos = (new_col, new_row)
                            
                            # Check if position is walkable and not important
                            if (terrain[new_row][new_col] == ' ' and 
                                new_pos not in important_tiles and
                                new_pos != other_player_pos):
                                safe_positions.append(new_pos)
            
            # If we found safe positions at this distance, stop searching
            if safe_positions:
                break
        
        # If no safe positions found, stay put
        if not safe_positions:
            return my_pos, []
        
        # Choose the closest safe position
        best_pos = min(safe_positions, key=lambda pos: abs(pos[0] - my_pos[0]) + abs(pos[1] - my_pos[1]))
        
        # Generate action plan to move to safe position
        my_ori = state.to_dict()["players"][self.agent_index]["orientation"]
        start_pair = (my_pos, tuple(my_ori))
        goal_pair = (best_pos, tuple(my_ori))  # Keep same orientation
        
        action_plan = self._get_action_plan(start_pair, goal_pair)
        
        return best_pos, action_plan

    def _parse_primary_action(self, response: str) -> str:
        """
        Parse the LLM response to extract only the human primary action prediction.
        Expected format:
          Primary: <primary_action_name>
        """
        # Default value
        predicted_human_action = "human_NOOP"
        
        # Parse primary action prediction
        primary_match = re.search(r'Primary:\s*(.+?)(?:\n|$)', 
                                 response, re.IGNORECASE)
        if primary_match:
            predicted_human_action = primary_match.group(1).strip()
        
        return predicted_human_action

    def _get_action_plan(self, start_pair, goal_pair):
        """Get action plan between two position/orientation pairs."""
        if self.mdp is None:
            return []
        terrain = self.mdp.terrain_mtx

        if self.planner is None:
            start_pos, start_ori = start_pair
            goal_pos, goal_ori = goal_pair
            return _bfs_fallback(start_pos, goal_pos, terrain, goal_ori)
        
        try:
            action_plan, _, _ = self.planner.get_plan(start_pair, goal_pair)
            return action_plan
        except KeyError:
            try:
                goal_pos, goal_ori = goal_pair
                action_plan, _, _ = self.planner.action_plan_from_positions(
                    [goal_pos], start_pair, goal_pair
                )
                return action_plan
            except Exception:
                start_pos, start_ori = start_pair
                goal_pos, goal_ori = goal_pair
                action_plan = _bfs_fallback(start_pos, goal_pos, terrain, goal_ori)
                return action_plan

    def _get_frontier_for_action(self, action: str, item: str, destination: str = None):
        """Get the appropriate frontier for a given action and item."""
        if action == "pickup":
            # Pickup actions - always from specific locations
            frontier_map = {
                "onion": self.onion_frontier,  # From onion dispenser
                "tomato": self.tomato_frontier,  # From tomato dispenser
                "chopped_onion": self.onion_chopping_frontier,  # From chopping station
                "chopped_tomato": self.tomato_chopping_frontier,  # From chopping station
                "dish": self.dish_frontier,  # From dish dispenser
                "soup": self.soup_staging_frontier,  # From soup staging
            }
            return frontier_map.get(item)
            
        elif action == "place":
            # Place actions - simplified destination logic
            if destination == "chopping_station":
                # Place at chopping station (only for onions and tomatoes)
                frontier_map = {
                    "onion": self.onion_chopping_frontier,
                    "tomato": self.tomato_chopping_frontier,
                }
                return frontier_map.get(item)
            elif destination == "staging_station":
                # Place at appropriate staging station (only for onions and tomatoes)
                frontier_map = {
                    "onion": self.onion_staging_frontier,
                    "tomato": self.tomato_staging_frontier,
                }
                return frontier_map.get(item)
            elif destination == "sink":
                # Place at sink station (for washing ingredients)
                frontier_map = {
                    "onion": self.sink_frontier,
                    "tomato": self.sink_frontier,
                }
                return frontier_map.get(item)
            else:
                # Default destinations for other items (no destination needed)
                frontier_map = {
                    "chopped_onion": self.onion_staging_frontier,  # Always to onion staging
                    "chopped_tomato": self.tomato_staging_frontier,  # Always to tomato staging
                    "dish": self.dish_staging_frontier,  # Always to dish staging
                    "soup": self.delivery_frontier,  # Always to serving station
                }
                return frontier_map.get(item)
            
        else:
            return None

    def _find_nearest_goal(self, choices, my_pos: tuple, my_ori: tuple) -> tuple:
        """Find the nearest goal from a list of choices."""
        if not choices:
            return (my_pos, tuple(my_ori))

        def sort_key(mo):
            (c, r), _ = mo
            # primary: Manhattan distance
            dist = abs(c - my_pos[0]) + abs(r - my_pos[1])
            # secondary: prefer smaller col, then smaller row
            return (dist, c, r)

        goal_pos, goal_orient = min(choices, key=sort_key)
        return (goal_pos, goal_orient)

    def _get_target_for_action(self, planned_action, my_pos):
        """Get the target position for a planned action."""
        action_lower = planned_action.lower()
        
        if "pickup" in action_lower:
            if "onion" in action_lower and self.onion_spawns:
                return min(self.onion_spawns, key=lambda pos: abs(pos[0] - my_pos[0]) + abs(pos[1] - my_pos[1]))
            elif "tomato" in action_lower and self.tomato_spawns:
                return min(self.tomato_spawns, key=lambda pos: abs(pos[0] - my_pos[0]) + abs(pos[1] - my_pos[1]))
            elif "dish" in action_lower and self.dish_spawns:
                return min(self.dish_spawns, key=lambda pos: abs(pos[0] - my_pos[0]) + abs(pos[1] - my_pos[1]))
        
        return None

    def _move_to_target(self, target, my_pos, my_ori):
        """Move to a specific target position."""
        if not target:
            return []
        
        # Create a simple frontier with just the target
        target_frontier = [(target, (0, 0))]  # No specific orientation needed
        
        goal = self._find_nearest_goal(target_frontier, my_pos, my_ori)
        start_pair = (my_pos, tuple(my_ori))
        return self._get_action_plan(start_pair, goal)

    def _parse_robot_action(self, robot_action):
        """
        Parse the robot action to get function name and item (like _parse_function_call in action_predictor.py).
        Expected format: pickup(onion) or place(onion, chopping_station) or NOOP
        """
        # Check for explicit NOOP
        if robot_action == "NOOP":
            return "NOOP", None

        # Parse pickup actions
        pickup_match = re.search(r'pickup\(([^)]+)\)', robot_action)
        if pickup_match:
            item = pickup_match.group(1).strip()
            if item in ["onion", "tomato", "chopped_onion", "chopped_tomato", "dish", "soup"]:
                return "pickup", item

        # Parse place actions with destination
        place_match = re.search(r'place\(([^,]+),\s*([^)]+)\)', robot_action)
        if place_match:
            item = place_match.group(1).strip()
            destination = place_match.group(2).strip()
            if item in ["onion", "tomato", "dish"] and destination in ["chopping_station", "staging_station", "sink"]:
                return "place", (item, destination)

        # Parse place actions without destination (for items with fixed destinations)
        place_simple_match = re.search(r'place\(([^)]+)\)', robot_action)
        if place_simple_match:
            item = place_simple_match.group(1).strip()
            if item in ["chopped_onion", "chopped_tomato", "dish", "soup"]:
                return "place", (item, "default")

        # final fallback
        return "pickup", "onion"

    def _move_to(self, action: str, item: str, start_pos: tuple, start_ori: tuple, destination: str = None):
        """Move to the appropriate location for the given action and item."""
        if action == "pickup":
            frontier_map = {
                "onion": self.onion_frontier,
                "tomato": self.tomato_frontier,
                "chopped_onion": self.onion_chopping_frontier,
                "chopped_tomato": self.tomato_chopping_frontier,
                "dish": self.dish_frontier,
                "soup": self.soup_staging_frontier,
            }
            choices = frontier_map.get(item)
        elif action == "place":
            if destination == "chopping_station":
                frontier_map = {
                    "onion": self.onion_chopping_frontier,
                    "tomato": self.tomato_chopping_frontier,
                }
                choices = frontier_map.get(item)
            elif destination == "staging_station":
                frontier_map = {
                    "onion": self.onion_staging_frontier,
                    "tomato": self.tomato_staging_frontier,
                    "dish": self.dish_staging_frontier,
                }
                choices = frontier_map.get(item)
            elif destination == "sink":
                frontier_map = {
                    "onion": self.sink_frontier,
                    "tomato": self.sink_frontier,
                }
                choices = frontier_map.get(item)
            else:
                frontier_map = {
                    "chopped_onion": self.onion_staging_frontier,
                    "chopped_tomato": self.tomato_staging_frontier,
                    "dish": self.dish_staging_frontier,
                    "soup": self.delivery_frontier,
                }
                choices = frontier_map.get(item)
        else:
            return []
        
        if not choices:
            return []
        
        goal = min(choices, key=lambda mo: abs(mo[0][0] - start_pos[0]) + abs(mo[0][1] - start_pos[1]))
        start_pair = (start_pos, tuple(start_ori))
        return self._get_action_plan(start_pair, goal)

    def PickUp(self, item, start_pos, start_ori):
        """Returns an action plan to pick up the specified item."""
        action_plan = self._move_to("pickup", item, start_pos, start_ori)
        # Only add INTERACT if it's not already in the plan
        if action_plan and Action.INTERACT not in action_plan:
            action_plan.append(Action.INTERACT)
        return action_plan

    def Place(self, item, start_pos, start_ori, destination: str = "default"):
        """Returns an action plan to place the specified item at the destination."""
        if destination == "default":
            action_plan = self._move_to("place", item, start_pos, start_ori, destination)
        else:
            action_plan = self._move_to("place", item, start_pos, start_ori, destination)
        
        # Only add INTERACT if it's not already in the plan
        if action_plan and Action.INTERACT not in action_plan:
            action_plan.append(Action.INTERACT)
        return action_plan

    def action(self, state):
        """Main action selection using optimized coordination system."""
        assert self.agent_index is not None, "agent_index is None in action!"
        

        
        # Get current state summary
        self.last_summary = self.summarize_state(state, {})
        print(f"Current position: {state.player_positions[self.agent_index]}")
        print(f"State summary: {self.last_summary}")
        
        # NEW: Get available primary actions directly from our unified state graph
        try:
            available_primary_actions = self._get_available_primary_actions_from_unified_graph(self.last_summary)
            print(f"Available primary actions from unified graph: {available_primary_actions}")
        except Exception as e:
            print(f"Error getting available actions from unified graph: {e}")
            available_primary_actions = []
        
        # FALLBACK: If no actions available from unified graph, provide basic actions
        if not available_primary_actions:
            print("⚠️  WARNING: No actions from unified graph, using fallback actions")
            available_primary_actions = [
                'Human Grab Onion',
                'Human Grab Chopped Onion', 
                'Human Grab Tomato',
                'Human Grab Chopped Tomato',
                'Human Grab dish',
                'Place onion in pot',
                'Place tomato in pot',
                'Turn stove on',
                'Pour soup',
                'Human Stage Soup',
                'Wash onion at sink',
                'Wash tomato at sink',
                'NOOP'
            ]
        
        # Generate plan to goal
        # TODO: Implement A* pathfinding for next_planned_action with new unified state graph
        # next_planned_action = self._generate_plan_to_goal(self.last_summary)
        # print(f"Next planned action: {next_planned_action}")
        next_planned_action = None  # Temporarily disabled
        
        # NEW: Use filtered primary tasks only for LLM context
        plan_text = ""
        if hasattr(self, 'primary_tasks') and self.primary_tasks:
            plan_lines = []
            for idx, primary_task in enumerate(self.primary_tasks):
                plan_lines.append(f"{idx+1}) {primary_task}")
            plan_text = "\n".join(plan_lines)
        else:
            plan_text = "No primary tasks available"
        
        # NEW: Use unified state graph instead of task-specific mechanics
        # The unified state graph handles all recipe types dynamically
        
        # Create optimized LLM prompt with EXACT rule-based conditions
        # This replaces the vague guidance with specific rules for each action type
        # MOST EFFICIENT NEXT ACTION FOR GOAL COMPLETION:
        # Next planned action: {next_planned_action}  # TODO: Re-enable when A* is implemented
        
        # prompt = f"""
        # CURRENT STATE:
        # {self.last_summary}

        # USER PLAN PRIMARY TASKS (Human Actions Only):
        # {plan_text}

        # AVAILABLE PRIMARY ACTIONS (from unified state graph):
        # {available_primary_actions}

        # **STRATEGY: Plan as Context, State Graph as Constraints**

        # The user's plan shows their preferred sequence and style of play. Use it to understand:
        # - What the user want to accomplish next
        # - Their preferred order of operations
        # - Their playing style and preferences

        # However, you MUST select from the available primary actions listed above. 

        # **DECISION PROCESS:**
        # 1. **Understand intent**: What does the user want to do next based on their plan?
        # 2. **Find semantic match**: Which available action best matches their intent?
        # 3. **Consider preferences**: If multiple actions match, prefer the one that follows their plan sequence
        # 4. **Select executable action**: Choose from the available state graph actions

        # **IMPORTANT:** You only need to predict the human's primary action. The robot will automatically coordinate its secondary actions using our optimized system.

        # Return only this line:
        # Primary: <human_action_name>
        # """

        prompt = f"""
        CURRENT STATE:
        {self.last_summary}

        USER PLAN PRIMARY TASKS (Human Actions Only):
        {plan_text}

        **CRITICAL RULE - AGENTS CANNOT PLACE INGREDIENTS IN POTS:**
        - Only humans can place ingredients in pots and interact with the stove
        - If an agent has an ingredient in hand, we cannot predict it to place it in the pot

        **PREDICTION RULES - ORDERED BY PRIORITY (HIGHEST TO LOWEST):**

        **HIGHEST PRIORITY:**
        **11. Human Stage Soup** ONLY when:
            - Someone is holding soup

        **10. Pour Soup** ONLY when:
           - The soup is ready AND 
           - Human is holding a dish AND

        **9. Human Grab Dish** ONLY when:
           - The soup is ready AND
           - Human is not holding a dish

        **8. Wait Till Ingredients Cooked** ONLY when:
           - The soup is cooking 

        **7. Turn Stove On** ONLY when:
           - ONLY When the soup is NOT cooking AND 
           - All required ingredients from the plan are in the pot

        **MEDIUM PRIORITY:**
        **MAKE SURE TO CHECK PLAN TO SEE IF INGREDIENTS NEED TO BE CHOPPED OR NOT**

        **1. Human Grab Onion** ONLY when:
           - The plan requires a NON-CHOPPED onion AND
           - There is no onion in the pot AND
           - There is no onion staged at the staging station

        **2. Human Grab Chopped Onion** ONLY when:
           - The plan requires a chopped onion AND
           - There is no onion in the pot AND
           - There is no onion staged at the chopping station or staging station

        **3. Human Grab Tomato** ONLY when:
           - The plan requires a NON-CHOPPED tomato AND
           - There is no tomato in the pot AND
           - There is no tomato staged at the staging station

        **4. Human Grab Chopped Tomato** ONLY when:
           - The plan requires a chopped tomato AND
           - There is no tomato in the pot AND
           - There is no tomato staged at the chopping station or staging station

        **5. Wash Onion at Sink** ONLY when:
           - The plan requires a washed onion AND
           - There is no onion at the sink AND
           - There is no onion in the pot AND
           - Human is holding an onion

        **6. Wash Tomato at Sink** ONLY when:
           - The plan requires a washed tomato AND
           - There is no tomato at the sink AND
           - There is no tomato in the pot AND
           - Human is holding a tomato

        **LOWEST PRIORITY:**
        **7. Place Onion in Pot** ONLY when:
           - ONLY when the onion is staged at the staging station AND
           - There is no onion in the pot AND

        **8. Place Tomato in Pot** ONLY when:
           - ONLY when the tomato is staged at the staging station AND
           - There is no tomato in the pot AND

        **PRIORITY ORDER - CHECK IN THIS SEQUENCE:**
        1. **FIRST**: Check if soup is in someone's hand → predict "Human Stage Soup" (PRIORITY 11)
        2. **SECOND**: Check if soup is ready → predict serving actions (PRIORITIES 9-10)
        3. **THIRD**: Check if soup is cooking → predict "Wait Till Ingredients Cooked" (PRIORITY 8)
        4. **FOURTH**: Check if ingredients are in pot but stove off → predict "Turn Stove On" (PRIORITY 7)
        5. **FIFTH**: Check if ingredients need washing → predict wash actions (PRIORITIES 5-6)
        6. **SIXTH**: Check if ingredients are missing → predict grab actions (look at plan for chopped or non-chopped) (PRIORITIES 1-4)
        7. **LAST**: Check if ingredients are staged → predict placement actions (PRIORITIES 7-8)

        **DECISION PROCESS:**
        1. **Check current state**: What's already in pot/cooking/ready?
        2. **Apply rules above**: Use the exact conditions for each action
        3. **Select action**: Choose the action that matches current state and plan requirements
        4. **Use the plan the user has provided to guide your decision and know their preferences (ingredients used / chopped or not)**
        5. **SELECT THE CHOICE FROM THE LIST OF AVAILABLE PRIMARY ACTIONS TO SELECT FROM**

        **CRITICAL RULE - BEFORE PREDICTING ACTIONS, CHECK THE LIST OF PREDICTION RULES ABOVE AND MAKE SURE YOU DO NOT VIOLATE ANY OF THEM**
        **WHEN YOU CHOOSE AN ACTION, GO THROUGH THE LIST OF PREDICTION RULES AND MAKE SURE YOU DO NOT VIOLATE ANY OF THE CONDITIONS FOR THAT ACTION**
        
        AVAILABLE PRIMARY ACTIONS TO SELECT FROM (from unified state graph):
        {available_primary_actions} or NOOP

        Return only this line:
        Primary: <human_action_name>
        """
        
        # Display essential information for testing
        print(f"STATE: {self.last_summary}")
                
        # Call LLM to get predictions
        response = query_openai(prompt, self.selected_model)
        
        # Parse the response - only need primary action now
        predicted_human_action = self._parse_primary_action(response)
        
        # Get robot action using our smart coordination system
        try:
            robot_action = quick_coordinate(self.last_summary, self.task_title, predicted_human_action)
        except Exception as e:
            print(f"Error getting robot action: {e}")
            robot_action = "NOOP"
        
        # Clean, essential debugging output
        print(f"PREDICTION: {predicted_human_action}")
        print(f"ROBOT: {robot_action}")
        
        # Convert high-level action to low-level movement
        my_pos = state.player_positions[self.agent_index]
        my_ori = state.to_dict()["players"][self.agent_index]["orientation"]
        
        if robot_action == "NOOP":
            # Check if blocking important tiles
            if self._is_blocking_important_tile(my_pos, state):
                safe_pos, action_plan = self._find_safe_position(my_pos, state)
                if action_plan:
                    move = action_plan[0] if action_plan else Action.STAY
                    return move, {
                        "predicted_human_action": predicted_human_action,
                        "robot_action": robot_action,
                        # "next_planned_action": next_planned_action,  # TODO: Re-enable
                        "llm_response": response,
                        "available_primary_actions": available_primary_actions,
                        "reasoning": "Moving to safe position to avoid blocking"
                    }
            
            # Stay in place
            return Action.STAY, {
                "predicted_human_action": predicted_human_action,
                "robot_action": robot_action,
                # "next_planned_action": next_planned_action,  # TODO: Re-enable
                "llm_response": response,
                "available_primary_actions": available_primary_actions,
                "reasoning": "No robot action needed"
            }
        
        # Execute the robot action using the EXACT same logic as action_predictor.py
        # FIXED: We now ALWAYS create new action plans instead of reusing old ones
        # This ensures the robot responds immediately to changing game states and predictions
        try:
            # ALWAYS create a new action plan based on the current robot action
            # This ensures we respond to changing game states and predictions
            # We no longer reuse old plans - each prediction gets a fresh action plan
            func_name, item = self._parse_robot_action(robot_action)
            print(f"Parsed robot action: {func_name}({item})")
            
            if func_name == "NOOP":
                # Check if the agent is blocking important tiles
                if self._is_blocking_important_tile(my_pos, state):
                    # If blocking, find a safe position to move to
                    safe_pos, action_plan = self._find_safe_position(my_pos, state)
                    if action_plan:
                        # Store the action plan and return first action
                        self.current_action_plan = action_plan
                        self.current_action_index = 1  # Start from second action next time
                        move = action_plan[0] if action_plan else Action.STAY
                        return move, {
                            "predicted_human_action": predicted_human_action,
                            "robot_action": robot_action,
                            # "next_planned_action": next_planned_action,  # TODO: Re-enable
                            "llm_response": response,
                            "available_primary_actions": available_primary_actions,
                            "blocking_prevention": True,
                            "action_plan": action_plan
                        }
                    else:
                        # If no safe move found, stay put
                        return Action.STAY, {
                            "predicted_human_action": predicted_human_action,
                            "robot_action": robot_action,
                            # "next_planned_action": next_planned_action,  # TODO: Re-enable
                            "llm_response": response,
                            "available_primary_actions": available_primary_actions,
                            "blocking_prevention": False,
                            "action_plan": []
                        }
                else:
                    # If not blocking, stay put
                    return Action.STAY, {
                        "predicted_human_action": predicted_human_action,
                        "robot_action": robot_action,
                        # "next_planned_action": next_planned_action,  # TODO: Re-enable
                        "llm_response": response,
                        "available_primary_actions": available_primary_actions,
                        "blocking_prevention": False,
                        "action_plan": []
                    }

            # Execute the compound action (EXACTLY like action_predictor.py)
            if func_name == "pickup":
                action_plan = self.PickUp(item, my_pos, my_ori)
            elif func_name == "place":
                if isinstance(item, tuple):
                    item_to_place, destination = item
                    action_plan = self.Place(item_to_place, my_pos, my_ori, destination)
                else:
                    action_plan = self.Place(item, my_pos, my_ori, "default")
            else:
                # Fallback to simple movement
                action_plan = [Action.STAY]

            # Store the action plan and return first action (EXACTLY like action_predictor.py)
            if action_plan:
                self.current_action_plan = action_plan
                self.current_action_index = 1  # Start from second action next time
                move = action_plan[0] if action_plan else Action.STAY
                print(f"Next Move: {move}")
                print(f"Full Action Plan: {action_plan}")
                
                return move, {
                    "predicted_human_action": predicted_human_action,
                    "robot_action": robot_action,
                    # "next_planned_action": next_planned_action,  # TODO: Re-enable
                    "llm_response": response,
                    "available_primary_actions": available_primary_actions,
                    "function_call": f"{func_name}({item})",
                    "action_plan": action_plan
                }
            else:
                return Action.STAY, {
                    "predicted_human_action": predicted_human_action,
                    "robot_action": robot_action,
                    # "next_planned_action": next_planned_action,  # TODO: Re-enable
                    "llm_response": response,
                    "available_primary_actions": available_primary_actions,
                    "function_call": f"{func_name}({item})",
                    "action_plan": []
                }
        
        except Exception as e:
            print(f"Error executing robot action: {e}")
            return Action.STAY, {
                "predicted_human_action": predicted_human_action,
                "robot_action": robot_action,
                # "next_planned_action": next_planned_action,  # TODO: Re-enable 
                "llm_response": response,
                "available_primary_actions": available_primary_actions,
                "reasoning": "Action execution failed, staying in place"
            }

    def actions(self, states, agent_indices):
        return [self.action(s) for s in states]
    
    def _filter_actions_by_plan(self, actions: List[str], primary_tasks: List[str]) -> List[str]:
        """
        Filter available actions based on plan context to show only relevant actions to LLM.
        Checks if the plan requires chopped or non-chopped ingredients and filters actions accordingly.
        This eliminates Human Grab Chopped Onion and Human Grab Onion depending on the plan (chopped or not).
        """
        if not primary_tasks or not actions:
            return actions
        
        print(f"🔍 Plan contains these primary tasks: {primary_tasks}")
        
        # Check what the plan requires for GRAB actions specifically
        plan_requires_chopped_onion = any("grab chopped onion" in task.lower() for task in primary_tasks)
        plan_requires_chopped_tomato = any("grab chopped tomato" in task.lower() for task in primary_tasks)
        plan_requires_regular_onion = any("grab onion" in task.lower() and "chopped" not in task.lower() for task in primary_tasks)
        plan_requires_regular_tomato = any("grab tomato" in task.lower() and "chopped" not in task.lower() for task in primary_tasks)
        
        print(f"🔍 Plan analysis (GRAB actions only):")
        print(f"   - Requires grab chopped onion: {plan_requires_chopped_onion}")
        print(f"   - Requires grab regular onion: {plan_requires_regular_onion}")
        print(f"   - Requires grab chopped tomato: {plan_requires_chopped_tomato}")
        print(f"   - Requires grab regular tomato: {plan_requires_regular_tomato}")
        
        # Filter actions based on plan requirements
        filtered_actions = []
        for action in actions:
            should_include = True
            
            # Handle onion actions
            if "Human Grab Chopped Onion" in action:
                should_include = plan_requires_chopped_onion
            elif "Human Grab Onion" in action:
                should_include = plan_requires_regular_onion
            
            # Handle tomato actions  
            elif "Human Grab Chopped Tomato" in action:
                should_include = plan_requires_chopped_tomato
            elif "Human Grab Tomato" in action:
                should_include = plan_requires_regular_tomato
            
            # Include all other actions (they don't have chopped/non-chopped variants)
            else:
                should_include = True
            
            if should_include:
                filtered_actions.append(action)
                print(f"🔍 Allowed '{action}' - matches plan requirements")
            else:
                print(f"🔍 Filtered out '{action}' - doesn't match plan requirements")
        
        print(f"🔍 Action filtering: {len(actions)} → {len(filtered_actions)} actions")
        print(f"🔍 Filtered actions: {filtered_actions}")
        
        return filtered_actions

    def _get_available_primary_actions_from_unified_graph(self, current_state: dict) -> List[str]:
        """
        NEW: Get available primary actions directly from our unified state graph.
        This replaces the old get_available_actions() call that was incompatible.
        """
        if not self.state_graph:
            print("Warning: No unified state graph available")
            return []
        
        try:
            # DEBUG: Print current state for debugging
            print(f"🔍 DEBUG: Current state: {current_state}")
            print(f"🔍 DEBUG: State graph has {len(self.state_graph.nodes)} nodes")
            print(f"🔍 DEBUG: State graph has {len(self.state_graph.state_to_node_id)} state mappings")
            
            # Find the current node in our unified state graph
            current_node_id = self._get_node_id_for_state(current_state)
            print(f"🔍 DEBUG: Found node ID: {current_node_id}")
            
            if not current_node_id:
                print(f"Warning: Could not find node for current state")
                return []
            
            # Get all edges from the current node
            edges = self.state_graph.get_edges_from(current_node_id)
            print(f"🔍 DEBUG: Found {len(edges) if edges else 0} edges from node {current_node_id}")
            
            if not edges:
                print(f"Warning: No transitions available from current state")
                return []
            
            # Extract the primary actions from the edges
            available_actions = []
            for edge in edges:
                if edge.action not in available_actions:
                    available_actions.append(edge.action)
            
            print(f"Found {len(available_actions)} available primary actions from unified graph")
            
            # Print current node ID and available actions for visibility
            print(f"🔍 Current state graph node: {current_node_id}")
            print(f"📋 Available actions from state graph: {available_actions}")
            
            # NEW: Apply plan-aware filtering to show only relevant actions to LLM
            if hasattr(self, 'primary_tasks') and self.primary_tasks:
                filtered_actions = self._filter_actions_by_plan(available_actions, self.primary_tasks)
                return filtered_actions
            else:
                print("No plan available for filtering, returning all actions")
                return available_actions
            
        except Exception as e:
            print(f"Error getting available actions from unified graph: {e}")
            import traceback
            traceback.print_exc()
            return [] 

 